Move the cleanup o c leanup section

diff --git a/e2e/test/lb-created-with-invalid-ip/chainsaw-test.yaml b/e2e/test/lb-created-with-invalid-ip/chainsaw-test.yaml
--- a/e2e/test/lb-created-with-invalid-ip/chainsaw-test.yaml
+++ b/e2e/test/lb-created-with-invalid-ip/chainsaw-test.yaml
@@ -38,6 +38,20 @@ spec:
         - describe:
             apiVersion: v1
             kind: Service
+      cleanup:
+        - script:
+            content: |
+              set -e 
+
+              delete_cm=$(kubectl delete configmap invalid-ip-config -n $NAMESPACE)
+              if [[ "$delete_cm" == "configmap \"invalid-ip-config\" deleted" ]]; then
+                echo "Configmap deleted successfully"
+              else
+                echo "Unable to delete the configmap: $delete_cm. Error: $delete_cm"
+              fi
+            check: 
+              ($error == null): true
+              (contains($stdout, 'Unable to delete the configmap')): false
     - name: Check that loadbalancer ip is not assigned
       try:
       - assert:
@@ -78,17 +92,8 @@ spec:
               if [[ "$service_ip" == "$invalid_ip" ]]; then
                 echo "Expected service ip to be null got the invalid ip: $invalid_ip"
               fi
-
-              delete_cm=$(kubectl delete configmap invalid-ip-config -n $NAMESPACE)
-              if [[ "$delete_cm" == "configmap \"invalid-ip-config\" deleted" ]]; then
-                echo "Configmap deleted successfully"
-              else
-                echo "Unable to delete the configmap: $delete_cm. Error: $delete_cm"
-              fi
-
             check:
               ($error == null): true
               (contains($stdout, 'Warning event not found')): false
               (contains($stdout, 'No invalid ip found in configmap')): false
-              (contains($stdout, 'Unable to delete the configmap')): false
               (contains($stdout, 'Expected service ip to be null got the invalid ip')): false
diff --git a/e2e/test/lb-created-with-specified-nb-id-reserved/chainsaw-test.yaml b/e2e/test/lb-created-with-specified-nb-id-reserved/chainsaw-test.yaml
--- a/e2e/test/lb-created-with-specified-nb-id-reserved/chainsaw-test.yaml
+++ b/e2e/test/lb-created-with-specified-nb-id-reserved/chainsaw-test.yaml
@@ -85,6 +85,38 @@ spec:
         - describe:
             apiVersion: v1
             kind: Service
+      cleanup:
+        - script:
+            content: |
+              set -e 
+
+              reserved_ip=$(kubectl get configmap nb-config -o=jsonpath='{.data.Reserved_IP}' -n $NAMESPACE)
+              if [ -z "$reserved_ip" ]; then
+                  echo "Error: No reserved ip found in configmap"
+              fi
+
+              delete_rip=$(curl -s --request DELETE \
+                -H "Authorization: Bearer $LINODE_TOKEN" \
+                -H "Content-Type: application/json" \
+                "${LINODE_URL}/v4beta/networking/reserved/ips/$reserved_ip" )
+
+              if [[ "$delete_rip" == "{}" ]]; then
+                echo "Reserved IP $reserved_ip deleted successfully"
+              else
+                echo "Unable to delete reserved ip: $reserved_ip. Error: $delete_rip"
+              fi
+
+              delete_cm=$(kubectl delete configmap nb-config -n $NAMESPACE)
+              if [[ "$delete_cm" == "configmap \"nb-config\" deleted" ]]; then
+                echo "Configmap deleted successfully"
+              else
+                echo "Unable to delete the configmap: $delete_cm. Error: $delete_cm"
+              fi
+            check:
+              ($error == null): true
+              (contains($stdout, 'No reserved ip found in configmap')): false
+              (contains($stdout, 'Unable to delete the configmap')): false
+              (contains($stdout, 'Unable to delete reserved ip')): false
     - name: Check that loadbalancer ip is assigned
       try:
       - assert:
@@ -134,29 +166,9 @@ spec:
               fi
               sleep 20
 
-              delete_rip=$(curl -s --request DELETE \
-                -H "Authorization: Bearer $LINODE_TOKEN" \
-                -H "Content-Type: application/json" \
-                "${LINODE_URL}/v4beta/networking/reserved/ips/$reserved_ip" )
-
-              if [[ "$delete_rip" == "{}" ]]; then
-                echo "Reserved IP $reserved_ip deleted successfully"
-              else
-                echo "Unable to delete reserved ip: $reserved_ip. Error: $delete_rip"
-              fi
-
-              delete_cm=$(kubectl delete configmap nb-config -n $NAMESPACE)
-              if [[ "$delete_cm" == "configmap \"nb-config\" deleted" ]]; then
-                echo "Configmap deleted successfully"
-              else
-                echo "Unable to delete the configmap: $delete_cm. Error: $delete_cm"
-              fi
-
             check:
               ($error == null): true
               (contains($stdout, 'No reserved ip found in configmap')): false
               (contains($stdout, 'No service ip found for service svc-test')): false
               (contains($stdout, 'IPs do not match')): false
               (contains($stdout, 'NB IDs do not match')): false
-              (contains($stdout, 'Unable to delete the configmap')): false
-              (contains($stdout, 'Unable to delete reserved ip')): false
