exit early on failures for reserved IP tests, fix variables in outputs, increase some timeouts and add retry on lb-with-proxyprotocol-default-annotation

diff --git a/e2e/test/lb-created-with-reserved-ip-change-ip-concurrently/chainsaw-test.yaml b/e2e/test/lb-created-with-reserved-ip-change-ip-concurrently/chainsaw-test.yaml
--- a/e2e/test/lb-created-with-reserved-ip-change-ip-concurrently/chainsaw-test.yaml
+++ b/e2e/test/lb-created-with-reserved-ip-change-ip-concurrently/chainsaw-test.yaml
@@ -29,6 +29,7 @@ spec:
               
               if ! [[ $reserved_ip =~ $re ]]; then
                   echo "Reserved ip [$reserved_ip] is incorrect, failed to create a reserved ip"
+                  exit 1
               fi
 
               reserved_ip2=$(curl -s --request POST \
@@ -42,6 +43,7 @@ spec:
               
               if ! [[ $reserved_ip2 =~ $re ]]; then
                   echo "Reserved ip [$reserved_ip2] is incorrect, failed to create a reserved ip"
+                  exit 1
               fi
               
               create_cm=$(kubectl -n $NAMESPACE create configmap reserved-ip-config --from-literal=ReservedIP=$reserved_ip --from-literal=ReservedIP2=$reserved_ip2 -o yaml --dry-run=client | kubectl apply -f -)
@@ -75,11 +77,13 @@ spec:
               reserved_ip=$(kubectl get configmap reserved-ip-config -o=jsonpath='{.data.ReservedIP}' -n $NAMESPACE)
               if [ -z "$reserved_ip" ]; then
                   echo "Error: No reserved ip found in configmap"
+                  exit 1
               fi
 
               reserved_ip2=$(kubectl get configmap reserved-ip-config -o=jsonpath='{.data.ReservedIP2}' -n $NAMESPACE)
               if [ -z "$reserved_ip2" ]; then
                   echo "Error: No reserved ip found in configmap"
+                  exit 1
               fi
 
               delete_rip=$(curl -s --request DELETE \
@@ -101,7 +105,7 @@ spec:
               if [[ "$delete_rip2" == "{}" ]]; then
                 echo "Reserved IP $reserved_ip2 deleted successfully"
               else
-                echo "Unable to delete reserved ip: $reserved_ip. Error: $delete_rip2"
+                echo "Unable to delete reserved ip: $reserved_ip2. Error: $delete_rip2"
               fi
 
               delete_cm=$(kubectl delete configmap reserved-ip-config -n $NAMESPACE)
@@ -142,11 +146,13 @@ spec:
               reserved_ip=$(kubectl get configmap reserved-ip-config -o=jsonpath='{.data.ReservedIP}' -n $NAMESPACE)
               if [ -z "$reserved_ip" ]; then
                   echo "Error: No reserved ip found in configmap"
+                  exit 1
               fi
 
               reserved_ip2=$(kubectl get configmap reserved-ip-config -o=jsonpath='{.data.ReservedIP2}' -n $NAMESPACE)
               if [ -z "$reserved_ip2" ]; then
                   echo "Error: No reserved ip found in configmap"
+                  exit 1
               fi
 
               parallel -j 2 patch_annotation ::: $reserved_ip2 "100.10.10.10"
@@ -187,16 +193,19 @@ spec:
               reserved_ip=$(kubectl get configmap reserved-ip-config -o=jsonpath='{.data.ReservedIP}' -n $NAMESPACE)
               if [ -z "$reserved_ip" ]; then
                   echo "Error: No reserved ip found in configmap"
+                  exit 1
               fi
 
               reserved_ip2=$(kubectl get configmap reserved-ip-config -o=jsonpath='{.data.ReservedIP2}' -n $NAMESPACE)
               if [ -z "$reserved_ip2" ]; then
                   echo "Error: No reserved ip found in configmap"
+                  exit 1
               fi
               
               service_ip=$(kubectl get svc svc-test -n $NAMESPACE -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
               if [ -z "$service_ip" ]; then
                   echo "Error: No service ip found for service svc-test"
+                  exit 1
               fi
               echo "{\"service_ip\": $service_ip}"
               echo "{\"reserved_ip\": $reserved_ip}"
